# Generated by Django 5.1.3 on 2024-11-13 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_birth_date_user_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='trip_type',
            field=models.CharField(blank=True, choices=[('lion', '사자'), ('owl', '부엉이'), ('monkey', '원숭이'), ('dolphin', '돌고래'), ('fox', '여우'), ('cat', '고양이')], max_length=20, null=True),
        ),
    ]
