# Generated by Django 4.2.16 on 2024-11-15 17:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('trip_time', models.CharField(max_length=50, null=True)),
                ('cost', models.CharField(max_length=50, null=True)),
                ('region', models.CharField(max_length=50)),
                ('rating', models.FloatField()),
                ('content', models.TextField(max_length=500)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='community_photos/')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('likes', models.ManyToManyField(blank=True, related_name='liked_communities', to=settings.AUTH_USER_MODEL)),
                ('scraps', models.ManyToManyField(blank=True, related_name='scrapped_communities', to=settings.AUTH_USER_MODEL)),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
