# Generated by Django 5.1.3 on 2024-11-11 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='community',
            old_name='trip_End',
            new_name='trip_end',
        ),
    ]
