# Generated by Django 5.1.3 on 2024-11-16 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='trip_timeUnit',
            field=models.CharField(choices=[('일', '일'), ('주', '주'), ('개월', '개월')], default='일', max_length=10),
        ),
        migrations.AlterField(
            model_name='community',
            name='trip_time',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
