# Generated by Django 5.1.1 on 2024-11-14 01:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='trip_End',
        ),
        migrations.RemoveField(
            model_name='community',
            name='trip_start',
        ),
        migrations.AddField(
            model_name='community',
            name='cost',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='community',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='community',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_communities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='community',
            name='scraps',
            field=models.ManyToManyField(blank=True, related_name='scrapped_communities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='community',
            name='trip_time',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='community',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='community',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='community_photos/'),
        ),
    ]
