# Generated by Django 4.2.16 on 2024-11-13 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='community',
            old_name='trip_End',
            new_name='trip_end',
        ),
    ]
