# Generated by Django 5.1.3 on 2024-11-16 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accompany', '0002_accompany_trip_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accompany',
            name='trip_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
